"""created user_role table

Revision ID: 00d242b0b2d6
Revises: e41a6f10952d
Create Date: 2022-01-16 01:47:19.285865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "00d242b0b2d6"
down_revision = "e41a6f10952d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_role",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.Enum("owner", "customer", name="roles"), nullable=True),
        sa.Column("role_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_role")
    # ### end Alembic commands ###
