"""empty message

Revision ID: 57aca16cd265
Revises: 00d242b0b2d6
Create Date: 2022-01-26 11:57:07.962073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "57aca16cd265"
down_revision = "00d242b0b2d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("brand", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "brand")
    # ### end Alembic commands ###
