"""create product_business_map table

Revision ID: 7e0c397d24c1
Revises: d5896a63b63f
Create Date: 2022-01-13 20:55:23.658572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7e0c397d24c1"
down_revision = "d5896a63b63f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_business_map",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("product_category_id", sa.BigInteger(), nullable=False),
        sa.Column("business_category_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["business_category_id"],
            ["business_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_category_id"],
            ["product_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_business_map")
    # ### end Alembic commands ###
