"""alter db table

Revision ID: 9f0c27fad0a9
Revises: be57680dd022
Create Date: 2022-01-14 13:03:45.725366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "9f0c27fad0a9"
down_revision = "be57680dd022"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("home_address", sa.String(length=500), nullable=True),
        sa.Column("contact_no", sa.String(length=15), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("customers", sa.Column("user_id", sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, "customers", "users", ["user_id"], ["id"])
    op.drop_column("customers", "name")
    op.drop_column("customers", "contact_no")
    op.add_column("owners", sa.Column("user_id", sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, "owners", "users", ["user_id"], ["id"])
    op.drop_column("owners", "home_address")
    op.drop_column("owners", "name")
    op.drop_column("owners", "contact_no")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "owners", sa.Column("contact_no", mysql.VARCHAR(length=15), nullable=True)
    )
    op.add_column("owners", sa.Column("name", mysql.VARCHAR(length=255), nullable=True))
    op.add_column(
        "owners", sa.Column("home_address", mysql.VARCHAR(length=500), nullable=True)
    )
    op.drop_constraint(None, "owners", type_="foreignkey")
    op.drop_column("owners", "user_id")
    op.add_column(
        "customers", sa.Column("contact_no", mysql.VARCHAR(length=15), nullable=True)
    )
    op.add_column(
        "customers", sa.Column("name", mysql.VARCHAR(length=255), nullable=True)
    )
    op.drop_constraint(None, "customers", type_="foreignkey")
    op.drop_column("customers", "user_id")
    op.drop_table("users")
    # ### end Alembic commands ###
