"""testss

Revision ID: dc93477434db
Revises: 369496780b5c
Create Date: 2022-01-13 16:36:49.017202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "dc93477434db"
down_revision = "369496780b5c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student2",
        sa.Column("id", mysql.INTEGER(display_width=11), nullable=False),
        sa.Column("enroll", mysql.INTEGER(display_width=11), nullable=True),
        sa.Column("personal_info", sa.JSON(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_on",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student2")
    # ### end Alembic commands ###
