"""created roles table

Revision ID: e41a6f10952d
Revises: 9f0c27fad0a9
Create Date: 2022-01-16 01:45:05.614244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e41a6f10952d"
down_revision = "9f0c27fad0a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
