import os

APP_ENV = os.getenv("APP_ENV")
APP_DEBUG = os.getenv("APP_DEBUG") in ["true", "True"]
LOG_LEVEL = os.getenv("LOG_LEVEL", "DEBUG")
DATABASE_PORT = os.getenv("DATABASE_PORT")
DATABASE_USER = os.getenv("DATABASE_USER")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD")
DATABASE_HOST=os.getenv("DATABASE_HOST")
DATABASE_NAME=os.getenv("DATABASE_NAME")
SENTRY_DSN = os.getenv("SENTRY_DSN")
ALLOWED_CORS_ORIGINS = os.getenv("ALLOWED_CORS_ORIGINS")
SENTRY_DSN = os.getenv("SENTRY_DSN")
LOGS_DIR = os.getenv("LOGS_DIR")
JWT_SECRET = os.getenv("JWT_SECRET")
ACCOUNT_SID = os.getenv("ACCOUNT_SID")
AUTH_TOKEN = os.getenv("AUTH_TOKEN")
SID = os.getenv("SID")
CLOUDINARY_CLOUD_NAME=os.getenv("CLOUDINARY_CLOUD_NAME")
CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY")
CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET")

