import os

# APP_ENV = os.getenv("APP_ENV")
# APP_DEBUG = os.getenv("APP_DEBUG") in ["true", "True"]
# LOG_LEVEL = os.getenv("LOG_LEVEL", "DEBUG")
# DATABASE_PORT = os.getenv("DATABASE_PORT")
# DATABASE_USER = os.getenv("DATABASE_USER")
# DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD")
# DATABASE_HOST=os.getenv("DATABASE_HOST")
# DATABASE_NAME=os.getenv("DATABASE_NAME")
# SENTRY_DSN = os.getenv("SENTRY_DSN")
# ALLOWED_CORS_ORIGINS = os.getenv("ALLOWED_CORS_ORIGINS")
# SENTRY_DSN = os.getenv("SENTRY_DSN")
# LOGS_DIR = os.getenv("LOGS_DIR")
# JWT_SECRET = os.getenv("JWT_SECRET")
# ACCOUNT_SID = os.getenv("ACCOUNT_SID")
# AUTH_TOKEN = os.getenv("AUTH_TOKEN")
# SID = os.getenv("SID")
# CLOUDINARY_CLOUD_NAME=os.getenv("CLOUDINARY_CLOUD_NAME")
# CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY")
# CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET")


APP_ENV = "local"
APP_DEBUG = True
LOG_LEVEL = "DEBUG"
DATABASE_PORT = 3356
DATABASE_USER = "root"
DATABASE_PASSWORD = "root"
DATABASE_HOST = "127.0.0.1"
DATABASE_NAME = "khunti_baazar"
LOGS_DIR = "/usr/src/backend/logs"
JWT_SECRET = "test_secret"


ACCOUNT_SID = "AC664166dcf9e0b7d28cb2898d137fb1df"
AUTH_TOKEN = "8eb7df78828fafdb65a879850385a1d5"
SID = "VAe5de2189dc789b1e2cddef2e546385a9"

CLOUDINARY_CLOUD_NAME = ("online-dukaan",)
CLOUDINARY_API_KEY = ("578656275387972",)
CLOUDINARY_API_SECRET = "HlxuAG4drY-uhBB2zTKaiPnWfqQ"
